name: TavernOperationsBP
version: 1.0
main: me.boyakabrodyaka.operation.Operation
api-version: 1.12
description: Управление таверной
author: BoyakaBrodyaka
depend: [TavernCoreBP, TavernCuisineBP, TavernCommerceBP]